name: Deploy Prod

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # FIX FOR YANDEX CLOUD
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2.22.35

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Upload to s3
        run: |
          aws s3 sync ./dist s3://wotstat.info \
            --cache-control "max-age=31104000, public" \
            --endpoint-url=https://storage.yandexcloud.net/ \
            --delete

          aws s3 cp \
            s3://wotstat.info/index.html s3://wotstat.info/index.html \
            --cache-control "public, max-age=300" \
            --endpoint-url=https://storage.yandexcloud.net/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ru-central1